name: publish

on: workflow_dispatch

jobs:
  Publish_Image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_AUTH_TOKEN }}

    - name: Build the hello-world Docker image
      run: |
        docker build . --tag ghcr.io/engineerakki/hello-world:latest
        docker push ghcr.io/engineerakki/hello-world:latest
        docker run ghcr.io/engineerakki/hello-world:latest

